spring.application.name=spring-ai-prompt-template-enquiry-assistant
server.port=8088
#mention our wished model to reduce cost..
spring.ai.openai.chat.options.model=gpt-5-nano
spring.ai.openai.api-key=${OPEN_AI_API_KEY}